name: yt_music
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/KRTirtho/yt_music

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.3.2
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  test: ^1.24.6
